version: "3.9"

services:
  silvester-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silvester-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:80"
    tty: true
